kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: mosquitto-ephemeral
spec:
  replicas: 1
  strategy:
    type: Rolling
  selector:
    name: mosquitto-ephemeral
  template:
    metadata:
      name: mosquitto-ephemeral
      labels:
        name: mosquitto-ephemeral
    spec:
      containers:
        - env: 
          - name: SOLUNAR_WS_LOG_LEVEL
            value: "1"
          name: mosquitto-ephemeral
          image: quay.io/b4mad/mosquitto-ephemeral:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1883 
              protocol: TCP
            - containerPort: 8883 
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 1883
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 1883
            timeoutSeconds: 1
          resources:
            limits:
              memory: 128Mi
          volumeMounts:
              - name: service-certificates
                mountPath: /etc/tls/service/
                readOnly: true
              - name: ca-bundle
                mountPath: /etc/tls/ca/
                readOnly: true
      volumes:
        - name: service-certificates
          secret:
            secretName: mosquitto-ephemeral
        - name: ca-bundle
          secret:
            secretName: config-service-cabundle
---
kind: Service
apiVersion: v1
metadata:
  name: mosquitto-ephemeral-tcp
spec:
  ports:
    - name: mosquitto-ephemeral-tcp
      port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    name: mosquitto-ephemeral
---
kind: Service
apiVersion: v1
metadata:
  name: mosquitto-ephemeral-tls
  service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer
  service.beta.openshift.io/serving-cert-secret-name: mosquitto-ephemeral
  service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer
spec:
  ports:
    - name: mosquitto-ephemeral-tls
      port: 8883
      protocol: TCP
      targetPort: 8883
  selector:
    name: mosquitto-ephemeral


